language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: Run Tests
      install: npm install
      script:
        - npm run test:ci
    - stage: Run Build
      install: npm install
      script:
        - npm install && npm run build:prod
        - tar czfv application.tgz static.json -C src/ index.css index.html js
    - stage: Deploy to github
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: src/
        github-token: $GITHUB_TOKEN
        repo: lakermann/elmulator
        keep-history: false
        target-branch: gh-pages
        on:
          branch: master