language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: Run Tests
      script:
        - npm install && npm run test:ci
    - stage: Run Build
      script:
        - npm install && npm run build:prod
        - tar czfv application.tgz static.json -C src/ index.css index.html js
