image: node:10.15.3

definitions:
  steps:
    - step: &runTests
        name: Run Tests
        caches:
          - node
        script:
          - npm install
          - npm run test:ci
    
pipelines:
  default:
    - step: *runTests
   